### ISSUE TITLE
follow method triggering rate limit

### ISSUE THREAD

**Issue by kazpsp** [sferik/twitter#534]
first here is my code:

``` ruby
class TwitterController < ApplicationController
  before_filter :twitterConnect

  def follow
    begin
      @response = @client.follow(params[:newFollower_id].to_i)
      respond_to do |format|
        format.js {  redirect_to :back}
        format.html {  redirect_to :back, :notice => "followed" }
      end  
    rescue Twitter::Error::TooManyRequests => error
      p 'tw_follower_ids sleep ' + error.rate_limit.reset_in.to_s
      flash[:error] = "Your rate limit has exceeded try again in "+error.rate_limit.reset_in.to_s+" seconds"
    end
  end

  private
  def twitterConnect
    if current_user.twitterToken && current_user.twitterSecret
      @client ||= Twitter::REST::Client.new do |config|
        config.consumer_key        = ENV['twitterKey'] 
        config.consumer_secret     = ENV['twitterSecret'] 
        config.access_token        = current_user.twitterToken
        config.access_token_secret = current_user.twitterSecret
      end
    else
      redirect_to root_url
    end
  end
```

when I follow several people i get rate limited, when i see where i get rate limited i can see its on: "/friends/ids" and on "/account/verify_credentials", im not sure if this is normal or is this some sort of bug.

thanks

**Comment by mikegrassotti** [comment]
This is because calling `connection.follow` is unbelievably expensive. It fetches a list of all existing friend_ids, paginated at 5K ids per API request. The `/friends/ids` API call has limit of 15 every 15-minutes so it's easy to hit the limit. See https://github.com/sferik/twitter/blob/master/lib/twitter/rest/friends_and_followers.rb#L108-L113

To get around this use `connection.follow!` which does what you'd expect, simply a POST to the `/friendships/create` API
