### ISSUE TITLE
Steaming API - updating filters/follows

### ISSUE THREAD

**Issue by pavoni** [sferik/twitter#565]
Have been using the Stream API to follow a number of users - no problems at all yet, so thanks guys! Also integrated very nicely with the REST API which allows me to back-populate data.

My question is around how to update a follow subscription. This is for the case where a new id is added to the database and so I need to add an additional follow to the stream subscription.

I guess it may be possible to just POST again to the twitter endpoint - but not 100% sure how I'd do that with the API (and whether it would work ok).

I'm working in a rails environment - and running the subscriber on a dedicated resque queue - so I could create a new stream client and then terminate the old one - but seems a bit ugly - plus might miss some data during the switch over.

Any thoughts or advice?

**Comment by josepjaume** [comment]
Hi @stve and @sferik ! This would be really useful to me as well. I'm working in an application where I need to track a set of keywords and send each of them through a separate queue. I ended up implementing it with threads, but just killing them when I no longer need them doesn't look like a clean solution.

AFAIK this was easier with `tweeetstream` as it used `EventMachine` and you could easily "talk" with the connection. Since now this is implemented in a blocking manner it will be difficult to close the connection from outside.

Is there anything I'm missing? Can I do something to help?

**Comment by josepjaume** [comment]
Oh, I just saw the discussion on: https://github.com/sferik/twitter/pull/631#issuecomment-78160920. Amazing work.

**Comment by jeremyhaile** [comment]
@stve what is currently the best way to close an existing stream and reconnect with a different set of filters?
