### ISSUE TITLE
Reply options are ignored unless the tweet starts with @username

### ISSUE THREAD

**Issue by fields** [sferik/twitter#566]
In the update method on this page: https://github.com/sferik/twitter/blob/master/lib/twitter/rest/tweets.rb

There should be a note in the method definition comments that the in_reply_to_status_id  and in_reply_to_status options are ignored unless the text of the tweet starts with the @username mention of the user who tweeted the tweet being replied to.

**Comment by P3rzival** [comment]
@sferik Amazing work here, I really appreciate the effort that building this must have taken you.

But... I just spent 5h trying to understand what was I doing wrong because I couldn't reply through the method that I was seeing in your docs. 

I've seen lots of posts on google with people asking the same thing so apparently a lot of people felt the same way but I couldn't find a solution until I realised that might be something to do with the gem and not with me, came back here and found that is something to do with the gem because of Twitter's rules. 

Again, love your work ❤️ , but could you just update the readme file or the gem documentation site so future users won't have to spend hours trying to find this issue? 😂  

I don't mean to be a pain, to be honest, it's my first time using the twitter API and I just started coding in ruby so I'm probably the person with less experience that will write on this issue, but precisely because of that, just wanted to tell you how hard it could be for newbies to find a solution for such a silly problem! 😂 

AGAIN, love your work mate 💘 

Keep doing what you do!

**Comment by stve** [comment]
@P3rzival Thanks for the feedback. Understanding Twitter's behavior can definitely cause confusion as well. Looking around we have an example reply in our documentation and the API documentation also includes a reference to the reply rules. What would have helped you further here?
