### ISSUE TITLE
User_timeline

### ISSUE THREAD

**Issue by alexshenia** [sferik/twitter#585]
why `client.user_timeline` return  only tweet id, but if i use user_timeline in twitter api console     user timeline return all inofrmation about tweet ??

**Comment by and0p** [comment]
I'm running into the same issue. My app needs to poll **all** the info shown in [Twitter's definition of user_timeline](https://dev.twitter.com/rest/reference/get/statuses/user_timeline), which includes all user and profile info, to attempt to determine if someone is a bot.

User_timeline is critical because the [`API limit is higher than any other`](https://dev.twitter.com/rest/public/rate-limits) (300 every 15 minutes). Currently, this gem is getting all that info but choosing to discard it. My only alternative using this gem is to combine info from `user_timeline(#, options)` and `user(#)`, but that restricts me to the other API method's lower rate limit.

I realize I'm not being helpful (I'd contribute to this project if I had the time currently) but it may make sense to have a separate function such as `user_timeline_tweets_only` that returns an array of tweets, and have `user_timeline` return a timeline object with an array of tweets as well as a user object.
