### ISSUE TITLE
#users endpoint is incorrect?

### ISSUE THREAD

**Issue by zuk** [sferik/twitter#662]
The #users method for querying users by user_id, screen_name, etc. seems to be using the wrong HTTP verb: https://github.com/sferik/twitter/blob/master/lib/twitter/rest/users.rb#L209

Shouldn't that be a GET rather than a POST? The POST does seem to work, but according to Twitter's docs, that should be a GET: https://dev.twitter.com/rest/reference/get/users/lookup

**Comment by sferik** [comment]
Quoting from the [documentation that you linked to](https://dev.twitter.com/rest/reference/get/users/lookup) (but apparently didn’t read):

> You are strongly encouraged to use a POST for larger requests.

Twitter does not specify what qualifies as “larger”, so I’ve opted to use POST for all requests. This may be slightly less efficient for smaller requests but the entire point of this endpoint/method is **bulk** lookup, so I think it’s safe to assume the number of users requested will be “larger”.

According to the HTTP 1.1 specification:

> Servers ought to be cautious about depending on URI lengths above 255 bytes, because some older client or proxy implementations might not properly support these lengths.

The non-query part of this URL (`https://api.twitter.com/1.1/users/lookup.json`) takes up 45 bytes. That leaves 210 for query parameters. The question mark (`?`) takes us down to 209.  We need to leave room to specify `include_entities=false` plus a joining ampersand (`&`), which gets us down to 186. `screen_name=` takes up 12, leaving us with 174 to actually specify Twitter screen names, which have a [maximum length of 20 characters](https://groups.google.com/forum/#!topic/twitter-development-talk/3HuhyNoycXc) (this has since been shortened to 15 characters, but you need to allow for legacy screen names). Further, names must be delimited by commas, so we must allow 21 bytes for each (except for the last). Taking the 174 bytes we have remaining and dividing that by 21, we can safely specify up to 8 screen names as query parameters in a `GET` request before we’d want to upgrade to `POST`.

I guess I’d be open to a pull request that uses `GET` when 8 or fewer users are specified but I’m not sure that the cost of the additional branching logic in the code is worth it. What are the benefits of using `GET` over `POST` (beyond the small optimization of being able to omit `Content-Length` and `Content-Type` headers)? Perhaps there is an argument for more correct HTTP semantics but the whole point of this gem is abstracting away the HTTP layer, so I’m not sure why anyone would care about that. Plus, that argument breaks down if `POST` is still being used when more than 8 users are specified.

**Comment by zuk** [comment]
Ah that makes sense. I've seen other `GET` calls to Twitter fail when the URL is too long. This does feel like abuse of the `POST` verb, but I'd rather have a questionable `POST` that always works than a more corect `GET` that mysteriously fails.

**Comment by sferik** [comment]
Dropbox has a nice [post](https://blogs.dropbox.com/developers/2015/03/limitations-of-the-get-method-in-http/) about a similar decision to use `POST` instead of `GET` with long parameter lists.
