### ISSUE TITLE
Twitter::NullObject returns true & nil

### ISSUE THREAD

**Issue by auxbuss** [sferik/twitter#720]
For years, I've had a piece of code that depends on the existence of a tweet's place:

    status['coords'] = tweet.place.bounding_box.coordinates if tweet.place

Yesterday, I spotted that this no longer does what the conditional suggests. However, it took a while to spot what was going on because of this:

     puts "place exists"        if tweet.place
     puts "place doesn't exist" if tweet.place.nil?

which returns:

    # "place exists"
    # "place doesn't exist"

An existential crisis! Eventually, I discovered that tweet.place now returns a Twitter::NullObject
https://github.com/sferik/twitter/blob/b299925d22d9ccf75c50328cea34e3f0194e1a33/lib/twitter/null_object.rb 

This strikes me as unexpected behaviour.

**Comment by sferik** [comment]
This is one of the [compromises](https://github.com/sferik/twitter/issues/704) of using a `Twitter::NullObject` instead of `nil`. On the flip side, the null object **prevents** surprises when an object is [unexpectedly `nil`](https://github.com/sferik/twitter/issues/415). For what it’s worth, this change was [specifically documented here](https://github.com/sferik/twitter/blob/eac5522edededacfc2a22d6f6879da43b8136d41/README.md#null-objects) as part of the version 4 release.

The canonical way to write your line of code is:

```ruby
status['coords'] = tweet.place.bounding_box.coordinates if tweet.place?
```

**Comment by auxbuss** [comment]
😱
