### ISSUE TITLE
RubyTCPSocket:87- TypeError: can't convert nil into String

### ISSUE THREAD

**Issue by 1dolinski** [sferik/twitter#726]
As a heads up, error shows on 5.15.0, not when using 5.14.0. 

TypeError: can't convert nil into String
initialize at org/jruby/ext/socket/RubyTCPSocket.java:87
new at org/jruby/RubyIO.java:851
stream at /Users/obedear/.rvm/gems/jruby-1.7.19/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16
request at /Users/obedear/.rvm/gems/jruby-1.7.19/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:119
sample at /Users/obedear/.rvm/gems/jruby-1.7.19/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:58
(root) at text.rb:22

https://gist.github.com/ebbflowgo/f7eab9f24214b64b0059

**Comment by nidev** [comment]
At [streaming/connection.rb](https://github.com/sferik/twitter/blob/925baa293ae3cb692b6a36be7cc9c5a39dff73c4/lib/twitter/streaming/connection.rb#L17) line 17,
```ruby
        client         = @tcp_socket_class.new(Resolv.getaddress(request.uri.host), request.uri.port)
```
TypeError is raised when either first one or second one is nil. On Jruby 9.0.1.0, the value of request.uri.port is nil.

Then, Where does 'request.uri' come from? It comes from http gem version 0.9.8, which is one of Twitter gem dependencies. 'request' object is made from HTTP::Request class. HTTP::Request has HTTP::URI class to parse URI from a string.

At [http/request.rb](https://github.com/httprb/http/blob/master/lib/http/request.rb#L177) line 177, there is a method named 'normalize_uri' which takes a string as a parameter. It parses and normalizes given uri string. Sadly, It doesn't pass 'port' parameter to newly created HTTP::URI object. That's the reason 'request.uri.port' is nil.

```ruby
    def normalize_uri(uri)
      uri = HTTP::URI.parse uri

      HTTP::URI.new(
        :scheme     => uri.normalized_scheme,
        :authority  => uri.normalized_authority,
        :path       => uri.normalized_path,
        :query      => uri.query,
        :fragment   => uri.normalized_fragment
      )
    end
```

I tried to modify the method to pass port directly, but it failed.
```
ArgumentError: Cannot specify both an authority and any of the components within the authority.
	from /home/nidev/.rbenv/versions/jruby-9.0.1.0/lib/ruby/gems/shared/gems/addressable-2.3.8/lib/addressable/uri.rb:783:in `initialize'
```

Okay. I found that if i define an authority properly, i can't put 'port' parameter. So, to get over this, use 'request.uri.default_port' instead of 'request.uri.port' in [streaming/connection.rb](https://github.com/sferik/twitter/blob/925baa293ae3cb692b6a36be7cc9c5a39dff73c4/lib/twitter/streaming/connection.rb#L17). Your problem can also occur on MRI 2.2.3, too.
```shell
irb(main):013:0> uri = normalize_uri('https://userstream.twitter.com:443/1.1/user.json')
=> #<HTTP::URI:0x2abea7a28e48 URI:https://userstream.twitter.com/1.1/user.json>
irb(main):014:0> uri.port
=> nil
irb(main):015:0> uri.default_port
=> 443
```
Finally, I changed connection.rb like this:
```ruby
        client = @tcp_socket_class.new(
          Resolv.getaddress(request.uri.host),
          request.uri.port.nil? ? request.uri.default_port : request.uri.port)
```
Though at least It worked for me, I hope you to confirm this fix and then, let's make a PR to get over this issue.
