### ISSUE TITLE
Finding out if a tweet is a reply to another tweet

### ISSUE THREAD

**Issue by pixeldesu** [sferik/twitter#739]
I'm working on a Twitter bot, and as it is picking people to reply to based on certain keywords they tweet. 

If the bot follows both users and one mentions another one including that keyword, the bot will reply to them, which is not wanted behaviour. (tl;dr the bot should only mention people that haven't replied to something)

Is there any way (besides checking for included `@mentions` in `Twitter::Tweet#text`) to find out if the tweet fetched from the userstream is a reply? I already tried it with `in_reply_to_tweet_id` but doesn't really work with the NullObjects returned.

**Comment by stve** [comment]
You can use `Twitter::Tweet#reply?` to check if the tweet is a reply:

```ruby
client = Twitter::REST::Client.new(credentials)
tweet = client.status("654766310170058752")

if tweet.reply?
  puts tweet.in_reply_to_screen_name
  puts tweet.in_reply_to_status_id
  puts tweet.in_reply_to_user_id
end
```

Note that if the reply is to a different user than the one posting the tweet, the message must have `@username` at the beginning of the message otherwise Twitter doesn't recognize it as a reply. There is an exception to that rule that applies when a user replies to themself (like the example above).
