### ISSUE TITLE
Proxy cannot be configured?

### ISSUE THREAD

**Issue by Tydax** [sferik/twitter#744]
Whenever I try to configure a proxy in the `Twitter::REST::Client` class, I get an exception, and it looks like it's coming from the gem.

```ruby
NoMethodError - undefined method `host=' for nil:NilClass:
    ~/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.2/lib/faraday/options.rb:31:in `block in update'
    ~/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.2/lib/faraday/options.rb:20:in `each'
    ~/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.2/lib/faraday/options.rb:20:in `update'
    ~/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.2/lib/faraday/options.rb:7:in `from'
    ~/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.2/lib/faraday/options.rb:231:in `from'
    ~/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:286:in `proxy'
    ~/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:83:in `initialize'
    ~/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.2/lib/faraday.rb:70:in `new'
    ~/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.2/lib/faraday.rb:70:in `new'
    ~/.rvm/gems/ruby-2.2.0/gems/twitter-5.15.0/lib/twitter/rest/client.rb:97:in `connection'
    ~/.rvm/gems/ruby-2.2.0/gems/twitter-5.15.0/lib/twitter/rest/request.rb:25:in `initialize'
    ~/.rvm/gems/ruby-2.2.0/gems/twitter-5.15.0/lib/twitter/rest/search.rb:30:in `new'
    ~/.rvm/gems/ruby-2.2.0/gems/twitter-5.15.0/lib/twitter/rest/search.rb:30:in `search'
```

I’m definitely no expert, so I may have done something wrong, but even when just copy-pasting the code provided in the examples, I still get a crash like this. Am I missing something?

**Comment by ranle** [comment]
I second this. I keep getting the same error when trying to use proxies.

**Comment by eduardbulai** [comment]
Ran into the same problem. The instructions form the documentation seems to be incorrect. I bypassed this by passing config.proxy = "http://proxy_ip:proxy_port" but it depends on your proxy config.

**Comment by hellojinjie** [comment]
As version 5.16, proxy did not work for Twitter::Streaming::Client ,

**Comment by gloaec** [comment]
So I digged into [faraday][1]'s connection library, which is used by the [twitter][2] gem to establish the connection to the API. Turns out that the proxy hash isn't expecting neither a `host` or a `port` attribute. Instead, it takes an `uri` attribute that must be an instance of `Addressable::URI` ([Check out the code here][3])

So, if you are using the Twitter: you must use the `Twitter::REST::Client` behind a proxy, here is how you must declare it :

    client = Twitter::REST::Client.new({
      consumer_key: "consumer_key",
      consumer_secret: "consumer_secret",
      access_token: "access_token_key",
      access_token_secret: "access_token_secret",
      proxy: {
        uri: Addressable::URI.parse("http://proxy_host:proxy_port"),
        username: "proxy_username",
        password: "proxy_password"
      }
    })

Hope this helps. Cheers !

  [1]: https://github.com/lostisland/faraday
  [2]: https://github.com/sferik/twitter
  [3]: https://github.com/lostisland/faraday/blob/master/lib/faraday/connection.rb

**Comment by Tydax** [comment]
Thanks for the tip! I can't test this right now, but considering the sources you've provided, your solution makes sense. I'm going to close the issue.
