### ISSUE TITLE
Can I use the firehose API

### ISSUE THREAD

**Issue by sylcvqnr** [sferik/twitter#766]
If I have access do the firehose's API, can I use it ?

**Comment by stve** [comment]
Hi @sylcvqnr we don't currently have a method that interfaces with this API, primarily because none of us have access to test it. We could certainly add support for it.

Having never had access myself, this is a bit of an assumption, but I'd imagine that with a large spike of tweets Ruby's performance may not be sufficient. Have you looked at Twitter's [Hosebird Client](https://github.com/twitter/hbc)?
