### ISSUE TITLE
update_with_media has been removed from the api

### ISSUE THREAD

**Issue by harshamv** [sferik/twitter#776]
Is there any way with this gem we can update the media with the tweet - now that the `update_with_media` seems to be deprecated

**Comment by majkelcc** [comment]
From https://dev.twitter.com/rest/reference/post/statuses/update_with_media

> Follow the Uploading media guide guide to upload one or more media entities, and then use POST statuses/update to attach them to a Tweet.

Both of these operations - [upload](http://www.rubydoc.info/gems/twitter/Twitter/REST/Media#upload-instance_method) and [update](http://www.rubydoc.info/gems/twitter/Twitter/REST/Tweets#update) - are available in this gem, so instead of:

    client.update_with_media(status, file)

you do:

    id = client.upload(file)
    client.update(status, media_ids: id.to_s)

**Comment by majkelcc** [comment]
https://github.com/sferik/twitter/blob/77238b540edfbc76aa2f25bc4398c3dad8f55edb/lib/twitter/rest/tweets.rb#L224 <-- it looks this is what gem is doing under the hood already

**Comment by calebthompson** [comment]
That change is in the unreleased version of the gem targeting a major version 6.
