### ISSUE TITLE
search results is empty

### ISSUE THREAD

**Issue by tchret** [sferik/twitter#931]
I'm trying to use this simple query:

```
search("from:Suhail since:2018-06-19 until:2018-06-21")
```

On twitter, the [query works well](https://twitter.com/search?since_id=1013764435531005952&q=from%3ASuhail%20since%3A2018-06-19%20until%3A2018-06-21&include_entities=1). But I get an empty array from the ruby client

![image](https://user-images.githubusercontent.com/4539476/42164995-f4ba4692-7e0f-11e8-9728-ffb7278135ce.png)

**Comment by samuelmaker** [comment]
+1 experiencing similar

**Comment by andypiper** [comment]
The standard search API [only supports a window of 7 days](https://developer.twitter.com/en/docs/tweets/search/overview), so this is expected behaviour. If you need to go back further you need the premium 30-day or full-archive search APIs. This is not something that is affected by whether or not you use the gem.
