### ISSUE TITLE
direct_messages/events/new => Could not authenticate you

### ISSUE THREAD

**Issue by rdlh** [sferik/twitter#949]
Gem version: `6.2.0`

I'm trying to send DMs to a user via the gem. When I try to send it, here's what's happening:

```
Twitter::REST::Request.new(@client, :json_post, "/1.1/direct_messages/events/new.json", payload).perform
```
> `NoMethodError: undefined method 'json_post' for #<HTTP::Client:0x007f80cda4b898>`

```
Twitter::REST::Request.new(@client, :post, "/1.1/direct_messages/events/new.json", payload).perform
```
> `{"errors":[{"message":"Could not authenticate you","code":32}]}`

Every API endpoint is working like a charm, but this one is not. Tried to send the request with [twurl](https://github.com/twitter/twurl), the request is working.

**Comment by FabienChaynes** [comment]
Hi,

As you can see [here](https://github.com/sferik/twitter/blob/v6.2.0/lib/twitter/rest/request.rb#L55) the `:json_post` request method was not yet supported on 6.2.0 but it is on [master](https://github.com/sferik/twitter/blob/master/lib/twitter/rest/request.rb#L55), and it's needed for DMs (looks like it was added with b45d545c7ebfd28e4d908037dd3fde04e3c307cf).

You can target a recent commit in your Gemfile instead of using the 6.2.0 to make it work before a new version is released.
